### ISSUE TITLE
cleanup hooks not firing

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt3#48]
Hi, 
it seems that cleanup hooks (like removing chef node and client) are not fired using the ovirt3 provider 
See also
https://github.com/mitchellh/vagrant/issues/6039
and 
https://github.com/pradels/vagrant-libvirt/issues/434

Thx a lot Christian

**Comment by myoung34** [comment]
I dont have any internal way of testing this, however I put the code into `1.7.1`

Can you verify this resolved it?

**Comment by alclonky** [comment]
Hi, 
they are fired now but i am getting an error:

==> default: Removing VM...
==> default: Auto-generating node name for Chef...
==> default: Running cleanup tasks for 'chef_client' provisioner...
==> default: Deleting node "vagrant-b7f0fc1e" from Chef server...
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

Thx Christian

**Comment by myoung34** [comment]
Can you test with the code from the `bugfix/48` branch?

**Comment by alclonky** [comment]
no same error
vagrant destroy
==> default: Removing VM...
==> default: Auto-generating node name for Chef...
==> default: Running cleanup tasks for 'chef_client' provisioner...
==> default: Deleting node "vagrant-b66b164d" from Chef server...
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

maybe its the same problem:
vagrant ssh -> works
vagrant ssh -c -> doesn't work (tells me its not running but vagrant status shows running)
vagrant ssh -c "date"
==> default: VM is not running. Please run `vagrant up` first.

**Comment by myoung34** [comment]
I'll investigate. I just fixed the previous fat-finger, so `1.8.0` and and `1.8.1` are gone forever. `1.8.2` is the latest.

I don't have access to a chef master which is what makes it hard to test

**Comment by alclonky** [comment]
does vagrant ssh -c work for you?
in both cases vagrant doesn't see the VM as "up"

**Comment by myoung34** [comment]
```
Marc-pc > myoung > example_box > master > vagrant ssh
[vagrant@asdf ~]$ logout
Connection to 192.168.2.91 closed.
Marc-pc > myoung > example_box > master > vagrant ssh -c 'whoami'
==> default: VM is not running. Please run `vagrant up` first.
```

Confirmed same behavior. Very likely related, i'll look into it later today.

**Comment by myoung34** [comment]
I got ssh_run working in `bugfix/48`. Can you test it with that change? Latest hash is `14190f4`

**Comment by myoung34** [comment]
ssh run is fixed in `1.9.0`, let me know if it resolves anything here

**Comment by alclonky** [comment]
ssh -c works now, but doesn't fix the cleanup Problem,
i don't now why but the VM is always destroyed before the cleanup happens
even with this order in action.rb
 b2.use ConnectOVirt
 b2.use ProvisionerCleanup
 b2.use DestroyVM

i did an debug run maybe this helps

[http://pastebin.com/ivApKSeX](http://pastebin.com/ivApKSeX)

**Comment by myoung34** [comment]
I think this might be a common issue, i found [this](https://github.com/mitchellh/vagrant-aws/issues/444)

I made that same change from the linked pr in the branch `bugfix/48` if you'd like to try that.

If no luck can you try both the published `1.9.0` gem and that branch on vagrant `1.7.4` ?

I hate using someone as a beta tester but it's much quicker than trying to write some tests right now since I don't even have a test framework. And a blackbox test might not find this issue, I'd have to write an actual integration test, which by then I'd end up having my own chef server. TL;dr: sorry.

**Comment by alclonky** [comment]
the change
b2.use ProvisionerCleanup, :before if defined?(ProvisionerCleanup)

did the Trick
vagrant destroy
==> default: Running cleanup tasks for 'chef_client' provisioner...
==> default: Deleting node "vagrant-7593001b" from Chef server...
==> default: Deleting client "vagrant-7593001b" from Chef server...
==> default: Removing VM...

As i am not a coder i am happy to help with testing. 
you plugin is very useful for me to get my setup running.

**Comment by myoung34** [comment]
Released in `1.9.1`

**Comment by alclonky** [comment]
you got an type  
b3.use vs.  b2.use 

action.rb:104:in `block (2 levels) in action_destroy': undefined local variable or method `b3' for VagrantPlugins::OVirtProvider::Action:Module (NameError)

sorry i haven't seen it before

**Comment by myoung34** [comment]
@alclonky created new ticket #55 
will fix tonight and in next release.
