### ISSUE TITLE
ca_no_verify ignored on plugin version >= 1.6.0

### ISSUE THREAD

**Issue by lpenz** [myoung34/vagrant-ovirt3#52]
Even when using the option, I get a SSL erro right away:
$ vagrant up --provider ovirt3
Error while connecting to oVirt: SSL_connect returned=1 errno=0 state=error: certificate verify failed
Error while connecting to oVirt: SSL_connect returned=1 errno=0 state=error: certificate verify failed
$

Reverting to version 1.5.0 solved the problem.

**Comment by myoung34** [comment]
Do you have your Vagrantfile?
Nothing has changed in the code that would affect `ca_no_verify` since that version

**Comment by myoung34** [comment]
I removed my server cert from `ca_bundle.crt` to verify:

```
Marc-pc > myoung > vagrant-ovirt3 > bugfix/56 > curl https://server.blindrage.local
curl: (60) SSL certificate problem: self signed certificate in certificate chain
```

In my vagrantfile I have `ca_no_verify=true` set:

```
Marc-pc > myoung > vagrant-ovirt3 > bugfix/56 > cd example_box/; vagrant up --provider=ovirt3; vagrant ssh -c 'whoami'; cd ..
Bringing machine 'default' up with 'ovirt3' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:              example_box_146
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Template:          vagrant-centos65
==> default:  -- Version:           0
==> default:  -- Datacenter:        local_dc
==> default:  -- Cluster:           local_cluster
==> default:  -- Console:           spice
==> default: Waiting for VM to become "ready" to start...
==> default: Starting VM.
==> default: Waiting for VM to get an IP address...
==> default: Waiting for SSH to become available...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine is booted and ready for use!
==> default: Rsyncing folder: /C/Users/myoung/repos/github/personal/vagrant-ovirt3/example_box/ => /vagrant
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
vagrant
Connection to 192.168.2.94 closed.
Marc-pc > myoung > vagrant-ovirt3 > bugfix/56 > cd example_box/; vagrant destroy -f; cd ..
==> default: Halting VM...
==> default: Waiting for VM to shutdown...
==> default: Removing VM...
Marc-pc > myoung > vagrant-ovirt3 > bugfix/56 > vi example_box/Vagrantfile


```

Then set it to `false` or remove the `ca_no_verify` line: 

```
Marc-pc > myoung > vagrant-ovirt3 > bugfix/56 > cd example_box/; vagrant up --provider=ovirt3; vagrant ssh -c 'whoami'; cd ..
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:921: warning: exception in verify_callback is ignored
Error while connecting to oVirt: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:921: warning: exception in verify_callback is ignored
Error while connecting to oVirt: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Comment by SriRamanujam** [comment]
Hi,

I've also run into this bug running version `1.9.2`. My Vagrantfile is as follows:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "builderbox1"

  config.vm.network :private_network,
      :ovirt__network_name => 'ovirtmgmt'

  config.vm.provider :ovirt3 do |ovirt|
      ovirt.template = 'ubuntu-xenial-img'
      ovirt.cpus = 2
      ovirt.memory = 3096
      ovirt.console = 'spice'
      ovirt.url = 'https://ovirt-server.internal/ovirt-engine/api:443'
      ovirt.username = 'admin'
      ovirt.password = 'password'
      ovirt.datacenter = 'Default'
      ovirt.ca_no_verify = true
      ovirt.disk_size = 15
  end
```

I have tried passing the following to `ovirt.url`:
 * `https://ovirt-server.internal:443`
 * `https://ovirt-server.internal/ovirt-engine:443`
 * `https://ovirt-server.internal/ovirt-engine/api:443`

None work.

**Comment by myoung34** [comment]
@SriRamanujam can you show the output from `vagrant up --provider=ovirt3 --debug` ?
Also it's just the URL of the server, not the API

```
  Vagrant.configure("2") do |config|
    config.vm.box = 'ovirt3'
    config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt3/blob/master/example_box/dummy.box?raw=true'
   config.vm.hostname = 'asdf'

    config.vm.provider :ovirt3 do |ovirt|
      ovirt.url = "https://server.blindrage.local:443"
      ovirt.username = "admin@internal"
      ovirt.password = "password"
      ovirt.datacenter = "local_dc"
      ovirt.template = "vagrant-centos65"
      ovirt.cpus = 1
      ovirt.memory = 512
      ovirt.ca_no_verify = true
   end
  end
```

**Comment by SriRamanujam** [comment]
re: the URL: all right, I just figured I'd be on the safe side and try a bunch of different possibilities.

I corrected the URL, and re-ran vagrant with debug. I've attached the log file.
[error.log.txt](https://github.com/myoung34/vagrant-ovirt3/files/264238/error.log.txt)

**Comment by myoung34** [comment]
I see your error log, unfortunately there's not much in it. I still can't replicate this on Windows or on Linux.

On Ubuntu 15.04 with vagrant `1.8.1` using plugin `1.9.3`

Without the `ca_no_verify` option in the Vagrantfile: 

```
marc-laptop  myoung  example_box  master  vagrant up --provider=ovirt3
/opt/vagrant/embedded/lib/ruby/2.2.0/net/http.rb:923: warning: exception in verify_callback is ignored
Error while connecting to oVirt: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

Adding `ovirt.ca_no_verify=true`: 

```
marc-laptop  myoung  example_box  master  vagrant up --provider=ovirt3
Bringing machine 'default' up with 'ovirt3' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:              example_box_146
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Template:          vagrant-centos65
==> default:  -- Version:           0
==> default:  -- Datacenter:        local_dc
==> default:  -- Cluster:           local_cluster
==> default:  -- Console:           spice
==> default: Waiting for VM to become "ready" to start...
==> default: Starting VM.
==> default: Waiting for VM to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine is booted and ready for use!
==> default: Rsyncing folder: /home/myoung/repos/github/vagrant-ovirt3/example_box/ => /vagrant
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
```

**Comment by myoung34** [comment]
Same output and works on Windows 10 using cygwin and Vagrant `1.7.4` with plugin version `1.9.3`
